export const API_USER = '/api/user'
export const API_USER_INFO = '/api/user/info'
export const API_USER_LIST = '/api/user/list'
export const API_USER_REGISTER = '/api/user/register'
export const API_USER_LOGIN = '/api/user/login'
export const API_USER_UPDATE = '/api/user/update'